
### Metadata
GET http://localhost:4004/my-capp-app/$metadata


###GET All Students
GET http://localhost:4004/my-capp-app/Students

###POST
POST http://localhost:4004/my-capp-app/Students
Content-Type: application/json

{
    "name" : "John Doe",
    "age" : 34
}